import {gql} from "@apollo/client";
export const address = 'Егорьевский проезд, 2Ас10';
export const number = '8 999 999 99 99'
export const GRAPHQL_ENDPOINT = 'https://0b18-188-126-35-179.eu.ngrok.io/graphql';
export const LOCALHOST = 'https://0b18-188-126-35-179.eu.ngrok.io'
export const FULL_ADDRESS = 'г. Москва, Егорьевский проезд, дом 1а, стр. 4'
export const MAIL = '24am@bbb.rent'
export const DOMAIN = 'arenda-mebeli24.ru'
export const GET_ALL_TITLES = gql`
    query getCategoryCards{
        kategoriis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    title
                    kategoriya{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    img{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                }
                id
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_ALL_CATEGORY_PAGES = gql`
    query getAllCategoryPages{
        categoryPages(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kategorii {
                        data {
                            id
                        }
                    }
                    metaData{
                        id
                        h1
                        description
                        metaDescription
                        metaHead
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    CatalogName
                    SEO{
                        text1
                        text2
                        text3
                        title1
                        title2
                        title3
                        img2{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        img1{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`

export const GET_ALL_PODBORKA_CARDS = gql`
    query getAllPodborkaCards{
        podborkas(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    PodborkaCard{
                        title
                        description
                        id
                        img{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    card_podborki{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }

    }
`
export const GET_ALL_PODBORKA_PAGES = gql`
    query getAllPodborkaPages{
        straniczaPodborkis(pagination:{page:1,pageSize:100}){

            data{

                attributes{

                    url
                    metaData{
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        description
                        id
                        h1
                        metaHead
                        metaDescription
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    CatalogName
                    SEO{
                        text1
                        text2
                        text3
                        title1
                        title2
                        title3
                        img2{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        img1{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_MAINPAGE_DATA = gql`
    query getAllPodborkaPages{
        mainPage{
            data{
                attributes{
                    SEO{
                        text1
                        text2
                        text3
                        title1
                        title2
                        title3
                        img2{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        img1{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    metaData{
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        h1
                        description
                        metaHead
                        metaDescription

                    }
                }
            }
           
        }
    }
`

export const GET_ALL_ADDITIONS_PROPS = gql`
    query getAdditionsProps{
        straniczaDopolnitelnojMebelis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    dopolnitelnaya_mebel{
                        data{
                            attributes{
                                Card{
                                    description
                                    theme
                                    id
                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    title
                                }
                            }
                        }
                    }
                    url
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_ALL_ADDITIONS_PAGES = gql`
    query getAllAdditionalsPages{
        straniczaDopolnitelnojMebelis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    metaData{
                        description
                        metaHead
                        metaDescription
                        h1
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    CatalogName
                    SEO{
                        text1
                        text2
                        text3
                        title1
                        title2
                        title3
                        img2{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        img1{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    url
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
            
        }
    }
`
export const GET_ALL_ALLCATALOG_CARDS = gql`
    query getAllCatalogCards{
        kartochkaKatalogas(pagination:{page:1,pageSize:100}){
            data{

                attributes{
                    stranicza_kategorii{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    CatalogCards{
                        mainImgArray{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        count
                        id
                        title
                        firstPrice
                        secondPrice
                        article

                        img{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        Complectation{
                            mainImgArray{
                                data{
                                    attributes{
                                        url
                                    }
                                }
                            }
                            title
                            article
                            firstPrice
                            secondPrice
                            count
                            img{
                                data{
                                    attributes{
                                        url
                                    }
                                }
                            }

                        }

                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_CATALOG_FILTERS = gql`
    query getCatalogFilters{
        categoryPages(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    filtrs{

                        data{
                            attributes{
                                stranicza_podkataloga{
                                    data{
                                        attributes{
                                            url
                                        }
                                    }
                                }
                                Filter{

                                    id
                                    title
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_SLIDER_CARDS = gql`
    query getSliderCards{
        categoryPages(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_slajderas{
                        data{
                            attributes{
                                SliderCard{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    title
                                    article
                                    firstPrice
                                    secondPrice
                                    count
                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_NEWS = gql`
    query getNews{
        novostis(pagination:{page:1,pageSize:100}){
            data{
                attributes{

                    card{
                        url
                        date
                        title
                        description
                        prevLink
                        prevTitle
                        nextImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        prevImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        nextLink
                        nextTitle
                        img{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        imgArray{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                    stranicza_novostej{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_NEWS_PAGES = gql`
    query getNewsPages{
        novostis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    stranicza_novostej{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_PODKATALOG_PAGES = gql`
    query getPodkatalog{
        straniczaPodkatalogas(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    metaData{
                        mainImg{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        id
                        h1
                        description
                        metaHead
                        metaDescription

                    }
                    CatalogName
                    SEO{
                        text1
                        text2
                        text3
                        title1
                        title2
                        title3
                        img2{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        img1{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_PODKATALOG_FILTERS = gql`
    query getPodkatalogFilters{
        straniczaPodkatalogas(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    stranicza_kategorii{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    url
                    filtrs{
                        data{
                            attributes{
                                Filter{
                                    id
                                    title
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_PODKATALOG_CARDS = gql`
    query getPodkatalogFilters{
        kartochkaKatalogas(pagination:{page:1,pageSize:100}){
            data{

                attributes{
                    stranicza_podkatalogas{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    CatalogCards{
                        mainImgArray{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        count
                        id
                        title
                        firstPrice
                        secondPrice
                        article

                        img{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                        Complectation{
                            mainImgArray{
                                data{
                                    attributes{
                                        url
                                    }
                                }
                            }
                            title
                            article
                            firstPrice
                            secondPrice
                            count
                            img{
                                data{
                                    attributes{
                                        url
                                    }
                                }
                            }

                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }

`
export const GET_PODKATALOG_SLIDER_CARDS = gql`
    query getSliderCards{
        straniczaPodkatalogas(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_slajderas{
                        data{
                            attributes{
                                SliderCard{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    count
                                    title
                                    article
                                    firstPrice
                                    secondPrice
                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_CATEGORY_FILTERS = gql`
    query getCatalogFilters{
        filtrs(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    stranicza_podborkis{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    Filter{
                        url
                        title
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_CATEGORY_CARDS = gql`
    query getCategoryCards{
        straniczaPodborkis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_katalogases{
                        data{
                            attributes{
                                CatalogCards{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    count
                                    id
                                    title
                                    firstPrice
                                    secondPrice
                                    article

                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_DOP_FILTERS = gql`
    query getDopFilters{
        filtrs(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    stranicza_dopolnitelnoj_mebelis{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    Filter{
                        url
                        title
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_DOP_CARDS = gql`
    query getCategoryCards{
        straniczaDopolnitelnojMebelis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_katalogas{
                        data{
                            attributes{
                                CatalogCards{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    count
                                    id
                                    title
                                    firstPrice
                                    secondPrice
                                    article

                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }

`
export const GET_ADDITIONAL_SLIDER_CARDS = gql`
    query getSliderCards{
        straniczaDopolnitelnojMebelis(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_slajderas{
                        data{
                            attributes{
                                SliderCard{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    count
                                    title
                                    article
                                    firstPrice
                                    secondPrice
                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_BUCKET_SLIDER_CARDS = gql`
    query getSliderCards{
        korzinas(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    url
                    kartochka_slajderas{
                        data{
                            attributes{
                                SliderCard{
                                    mainImgArray{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    count
                                    title
                                    article
                                    firstPrice
                                    secondPrice
                                    img{
                                        data{
                                            attributes{
                                                url
                                            }
                                        }
                                    }
                                    Complectation{
                                        mainImgArray{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }
                                        title
                                        article
                                        firstPrice
                                        secondPrice
                                        count
                                        img{
                                            data{
                                                attributes{
                                                    url
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_MENU_CARDS = gql`
    query menuCards {
        kartochkaMenyus(pagination:{page:1,pageSize:100}){
            data{
                attributes{
                    stranicza_kategorii{
                        data{
                            attributes{
                                url
                            }
                        }
                    }
                    MenuCard{
                        title
                        img{
                            data{
                                attributes{
                                    url
                                }
                            }
                        }
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
export const GET_FOOTER_CARDS = gql`
    query FooterCards {
        futers(pagination:{page:1,pageSize:100}){
            data
            {
                id
                attributes{
                    FooterCard{
                        title
                        column
                    }
                }
            }
            meta{
                pagination{
                    pageSize
                    page
                }
            }
        }
    }
`
